version: "3"
services:
  monitor-app:
    image: prom/prometheus
    ports:
      - 9090:9090
    restart: always
    volumes:
     - ./monitor-app/prometheus.yml:/etc/prometheus/prometheus.yml
     - ./monitor-app/data:/etc/prometheus/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
  visualize-app:
    image: grafana/grafana-enterprise
    ports:
      - 3000:3000
    restart: always
    user: "$UID:$UID"
    volumes:
      - ./visualize-app/data:/var/lib/grafana

